#' Perform general RainFARM downscaling.
#'
#' @param r Large-scale array to downscale.
#' Spatial downscaling is performed separately for each element of the third dimension of `r`.
#' @param slope Spatial spectral slope.
#' @param nf Refinement factor for spatial downscaling.
#' @param weights Weights for orographic downscaling generated by the `rfweight()`function.
#' @param fglob Logical to conserve global average over domain.
#' @param fsmooth Logical to use smoothing instead of gridpoint conservation.
#' @param verbose Logical to provide some progress report.
#' @return The downscaled array.
#' @export

rainfarm <- function(r, slope, nf, weights=1.,
                     fglob=FALSE, fsmooth=FALSE, verbose=FALSE) {
  drop=FALSE
  nax <- dim(r)[1]
  nay <- dim(r)[2]
  nt <- dim(r)[3]
  if ( is.na(nt) ) {
    drop=TRUE
    nt <- 1
  }

  if ( nax == nay ) {
    nas <- nax
  } else {
    stop("The spatial dimensions of input array must be square")
  }

  ns <- nas * nf
  f <- initmetagauss(slope, ns)
  rd <- array(0., c(ns, ns, nt))

  for (k in 1:nt) {
    if (verbose) {
       print(paste0("Frame ", k))
    }
    r1 <- r[ , , k]
    if (mean(r1) == 0.) {
        rd[ , , k] <- matrix(0., ns, ns)
    } else {
        fm <- downscale(r1, f, weights, fglob = fglob, fsmooth = fsmooth)
        rd[ , , k] <- fm
    }
  }
  if (drop) {
    rd <- drop(rd)
  }
  return(rd)
}
